xconfig update

diff --git a/xconfig b/xconfig
--- a/xconfig
+++ b/xconfig
@@ -1,39 +1,113 @@
 #!/bin/bash
 
+function install_apt_repository {
+  local url
+  case "${1}" in
+    cmake) url="https://apt.kitware.com/kitware-archive.sh";;
+    llvm)  url="https://apt.llvm.org/llvm.sh";;
+  esac
+  test -n "${url}" && sudo bash -c "$(curl -sL ${url})"
+}
+
+function findname {
+  local out
+  local name="${1}"; shift
+  while [ "${1}" ]; do
+    out="$(find "${1}" -name "${name}" )"
+    test -n "${out}" && break
+  done
+  echo "${out}"
+}
+
+function promptYN {
+  echo -ne "${1} "; read -p "[Y|n]" out
+  case $out in
+    y|Y) echo -ne "\e[1A\e[2K"; return 0;;
+    *)   return 1;;
+  esac
+}
+
+function llvm_mingw_latest {
+  curl -sL "https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
+}
+
+function llvm_mingw_install {
+  # install llvm-mingw
+  XB_LLVM_MINGW_JSON=$(curl -sL "https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest")
+  XB_LLVM_MINGW_LATEST="$(jq -r .tag_name <<<"${XB_LLVM_MINGW_JSON}")"
+  : "${LLVM_MINGW_HOME:=${HOME}/llvm-mingw}"
+  local url="$(jq -r -M '.assets[] | .browser_download_url' <<<"${XB_LLVM_MINGW_JSON}" | grep '.*ucrt.*ubuntu.*'"$(uname -p)")"
+  pushdir "$(pwd)"
+  export LLVM_MINGW_HOME
+  safe_cd "$(dirname ${LLVM_MINGW_HOME})"
+  safe_rm "${LLVM_MINGW_HOME}"
+  
+  wget_untar "${url}" "llvm-mingw"    
+  echo "${XB_LLVM_MINGW_LATEST}" >"${LLVM_MINGW_HOME}/version"
+  export XB_LLVM_MINGW_CLANG_VERSION="$("${LLVM_MINGW_HOME}/bin/clang" -dumpversion)"
+  popdir
+}
+
 function check_install {
-    local v0
-    local v1
-    for p in $@; do
-        v0=$(dpkg-query -W $p 2>/dev/null | cut -f2)
-        v1=$(apt-cache madison $p | cut -d '|' -f2 | head -n1 | xargs)
-        if [ -z "${v0}" ];then
-            printf "${CH}${XBTAB}: ${C0}%s\n" "  $p" "installing..."
-            printf "$(${apt_install} $p -y 2>/dev/null | grep $p | sed "s/^$p//" | head -n1)\n"
-        elif [ "${v1}" == "${v0}" ]; then
-            printf "${CH}${XBTAB}: ${C0}%s\n" "  $p" "${v0}"
-        else
-            printf "${CH}${XBTAB}: ${C0}%s" "  $p" "${v0} upgrading to..."
-            printf "$(${apt_install} $p -y 2>/dev/null | grep $p | sed "s/^$p//" | head -n1)\n"
-        fi  
-    done
+  local v0 v1 out
+  for p in $@; do
+    v0=$(dpkg-query -W "$p" 2>/dev/null | cut -f2)
+    v1=$(apt-cache madison "$p" | cut -d '|' -f2 | head -n1 | xargs)
+    if [ -z "${v0}" ];then
+      printf "${CH}${XBTAB}: ${C0}%s\n" "  $p" "installing..."
+      out=$(${apt_install} "${p}" -y 2>/dev/null | grep "${p}" | sed "s/^${p}//" | head -n1)
+      printf "%s\n" "$out"
+    elif [ "${v1}" == "${v0}" ]; then
+      printf "${CH}${XBTAB}: ${C0}%s\n" "  $p" "${v0}"
+    else
+      printf "${CH}${XBTAB}: ${C0}%s" "  $p" "${v0} upgrading to..."
+      out=$(${apt_install} "${p}" -y 2>/dev/null | grep "${p}" | sed "s/^${p}//" | head -n1)
+      printf "%s\n" "${out}"
+    fi  
+  done
 }
 
 # synthax: check_slink <dest> <src>
 function check_slink {
   local status
 	if [ ! -f "${1}" ]; then
-		sudo ln -s "${2}" "${1}" 2>&1 >/dev/null && status="new" || status="${CR1}err${C0}"
+		sudo ln -s "${2}" "${1}" > /dev/null && status="new" || status="${CR1}err${C0}"
     ${verbose} && printf "${CC1}%-6s ${C0}%-60s-> ${CW}%s\n" "    ${status}" "${1}" "${2}"
-	elif [ "$(readlink ${1})" == "${2}" ]; then
+	elif [ "$(readlink "${1}")" == "${2}" ]; then
     ${verbose} && printf "${CH}%-6s ${CD}%-60s-> ${C0}%s\n" "    ok" "${1}" "${2}"
   else
-    sudo ln -s "${2}" "${1}" 2>&1 >/dev/null && status="${CY1}upd${C0}" || status="${CR1}err${C0}"
+    sudo ln -s "${2}" "${1}" > /dev/null && status="${CY1}upd${C0}" || status="${CR1}err${C0}"
     ${verbose} && printf "${CC1}%-6s ${C0}%-60s-> ${CW}%s\n" "    ${status}" "${1}" "${2}"
   fi
 }
 
 function check_ndk_symlink {
-    [[ -z "$(readlink "$1" | grep ${ANDROID_NDK_HOME})" ]]
+  [[ -z "$(readlink "$1" | grep "${ANDROID_NDK_HOME}")" ]]
+}
+
+function check_ndk_symlink_test {
+  [[ -z "$(readlink "$1" | grep "${ANDROID_NDK_HOME}")" ]]
+}
+
+# syntax check_ndk_symlink_dir <dest-symlink> <src> [<src_root> <src_root_name>]
+function check_ndk_symlink_dir {
+  local quiet=false
+  test "${1}" = "--quiet" && quiet=true && shift
+  local dst="${1}"
+  local src="${2}"
+  local srcname="${src//${3}/${4}}"  
+  local status
+  if [ -L "${dst}" ]; then
+    if [ "$(readlink "${dst}")" == "${src}" ]; then
+      status="${CW}ok${CD}"
+    else
+      sudo ln -sfn "${src}" "${dst}" && status="${CY1}updated${CD}" || status="${CR1}failed${CD}"
+    fi
+  else
+    sudo ln -sfn "${src}" "${dst}" && status="${CY1}created${CD}" || status="${CR1}failed${CD}"
+  fi
+  echo -ne "\n    ${C0}$(basename "${dst}")${CD} symlink ${status}"
+  ! ${quiet} && echo -ne ": ${dst} -> ${srcname}"
 }
 
 # synthax check_clang_wrapper [--overwrite] <triplet> <clang|clang++> <args>
@@ -43,7 +117,7 @@ function check_clang_wrapper {
     --overwrite) shift; overwrite=true;;
   esac
 	if ${overwrite} || [ ! -f "/usr/${1}/bin/${2}" ]; then
-		cat <<-eof | sudo tee /usr/${1}/bin/${2} >/dev/null
+		cat <<-eof | sudo tee "/usr/${1}/bin/${2}" >/dev/null
 			#!/bin/bash
 			${2} ${3} "\$@"
 			eof
@@ -62,7 +136,7 @@ function check_ndk_wrapper {
 			#!/bin/bash
 			\${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/${2}\${API:=${NDK_API_DEFAULT}}-${1} "\$@"
 			eof
-    sudo chmod +x ${3}
+    sudo chmod +x "${3}"
   fi
 }
 
@@ -101,7 +175,7 @@ XB_CLANG_PKGLIST='clang-format clang-tidy clang-tools clang clangd libc++-dev
 : "${build_cpu:=$(uname -m)}"
 
 # Header
-printf "\n${CC1}This Machine:\n"
+echo -e "\n${CC1}This Machine:"
 printf "${CH}${XBTAB}: ${C0}%s\n" '  build arch' ${build_arch}
 printf "${CH}${XBTAB}: ${C0}%s\n" '  build os' ${build_os}
 printf "${CH}${XBTAB}: ${C0}%s\n" '  build cpu' ${build_cpu}
@@ -120,8 +194,8 @@ check_install curl patch jq lzip unzip
 
 # GNU gcc compiler
 
-printf "\n${CC1}${b}Gnu compiler\n"
-check_install gcc g++
+echo -e "\n${CC1}${b}Gnu compiler"
+check_install ${XB_GCC_PKGLIST}
 XB_BUILD_GCC="$(command -v gcc)"
 test -z "${XB_BUILD_GCC}" && exit_err "Unable to install gcc. Aborting."
 XB_GCC_VERSION="$(${XB_BUILD_GCC} -dumpversion)"
@@ -133,14 +207,14 @@ gnu_cross_archlist="x86_64-linux-gnu i686-linux-gnu aarch64-linux-gnu arm-linux-
 gnu_cross_archlist="${gnu_cross_archlist//$(gcc -print-multiarch)/}"
 
 for gcross in ${gnu_cross_archlist}; do
-  printf "${CC1} Gnu ${gcross} cross-compiler\n"
+  printf "${CC1} Gnu %s cross-compiler\n" "${gcross}"
   case "${gcross}" in
     aarch64*) check_install ${XB_GCC_ARM64_PKGLIST};;
     arm*)     check_install ${XB_GCC_ARMHF_PKGLIST};;
     i686*)    check_install ${XB_GCC_I686_PKGLIST};;
     x86_64*)  check_install ${XB_GCC_X86_64_PKGLIST};;
   esac
-  printf "${CH}${XBTAB}: ${C0}%s\n\n" "  version" "$(${gcross}-gcc -dumpversion)"
+  printf "${CH}${XBTAB}: ${C0}%s\n\n" "  version" "$("${gcross}-gcc" -dumpversion)"
 done
 
 XB_GCC_TOP_VER=$(apt search gcc 2>/dev/null | grep -oP 'gcc-[0-9\.]+' | sed 's,gcc-,,' | sort -n |tail -n1)
@@ -154,7 +228,7 @@ fi
 
 # LLVM-CLANG compiler
 
-printf "\n${CC1}${b}Clang compiler\n"
+echo -e "\n${CC1}${b}Clang compiler"
 XB_BUILD_CLANG="$(command -v clang)"
 if [ -z "${XB_BUILD_CLANG}" ]; then
   PS3='LLVM not installed: '
@@ -172,11 +246,11 @@ if [ -n "${XB_BUILD_CLANG}" ]; then
   XB_BUILD_CLANG_VERSION_MAJOR=${XB_BUILD_CLANG_VERSION%%\.*}
   printf "${CH}${XBTAB}: ${C0}%s\n" "  found at" "${XB_BUILD_CLANG}"
   printf "${CH}${XBTAB}: ${C0}%s\n\n" "  version" "$(${XB_BUILD_CLANG} -dumpversion)"
-  printf "\n${CC1} Clang components\n"
-  check_install ${XB_CLANG_PKGLIST} libllvmlibc-${XB_BUILD_CLANG_VERSION_MAJOR}-dev
+  echo -e "\n${CC1} Clang components"
+  check_install ${XB_CLANG_PKGLIST} "libllvmlibc-${XB_BUILD_CLANG_VERSION_MAJOR}-dev"
 
   # check symlinks
-  printf "\n${CC1} Clang symlinks"
+  echo -ne "\n${CC1} Clang symlinks"
   
   cl=(aarch64 arm i686 x86_64)
 	ab=(arm64 armhf i386 x86_64)
@@ -191,60 +265,58 @@ if [ -n "${XB_BUILD_CLANG}" ]; then
     t="${cl[$a]}-linux-${abi[$a]}"
     # skip native arch
     test "${t}" = "${build_arch}" && continue
-    
-    printf "\n${CH}  ${t}\n"
+    dst_bin="/usr/${t}/bin"
+    echo -ne "\n${CH}  ${t}"
     
     # create cross arch dir at /usr
-    [ -d "/usr/${t}/bin" ] || sudo mkdir -p "/usr/${t}/bin"
+    [ -d "${dst_bin}" ] || sudo mkdir -p "${dst_bin}"
 
     # symlinks for llvm utils
-    printf "    ${CD}"
+    echo -ne "    ${CD}"
     for e in ${exe}; do
-      check_slink "/usr/${t}/bin/llvm-${e}" "/usr/bin/llvm-${e}"
-      ${verbose} || printf "${e} "
+      check_slink "${dst_bin}/llvm-${e}" "/usr/bin/llvm-${e}"
+      ${verbose} || echo -ne "${e} "
     done
     
     # symlinks for ld
-    check_slink "/usr/${t}/bin/ld.lld" "/usr/bin/ld.lld"
+    check_slink "${dst_bin}/ld.lld" "/usr/bin/ld.lld"
     
     # clang/clang++ wrapper
     wrapper_args="--target=${t}"
     test "${ab[${a}]}" = "armhf" && wrapper_args+=' -mfloat-abi=hard -mfpu=neon' 
     check_clang_wrapper --overwrite "${t}" 'clang' "${wrapper_args}"
     check_clang_wrapper --overwrite "${t}" 'clang++' "${wrapper_args}"
-    ${verbose} || printf "\n    clang/clang++ wrapper with args: ${wrapper_args}\n"
+    ${verbose} || echo -e "\n    clang/clang++ wrapper with args: ${wrapper_args}"
 	done
 fi
 
 
-
-
 # Android NDK CLANG compiler
 
-printf "\n${CC1}${b}Android NDK compiler\n"
+echo -e "\n${CC1}${b}Android NDK compiler"
 if [ ! -d "${ANDROID_NDK_HOME}" ]; then
-  printf "${CH}ANDROID_NDK_HOME is not defined\n"
+  echo -e "${CH}ANDROID_NDK_HOME is not defined"
   ndk_dir="$(find ~ -name 'ndk-lldb' | head -n1)"
   if [ -f "${ndk_dir}" ]; then
-    ndk_dir="$(dirname ${ndk_dir})"
+    ndk_dir="$(dirname "${ndk_dir}")"
     export ANDROID_NDK_HOME="${ndk_dir}"
   else
-    printf "${CY1}Android NDK not found.\n"
+    echo -e "${CY1}Android NDK not found."
     url="$(curl -sL https://developer.android.com/ndk/downloads | grep -Po "https://dl.google.com/android/repository/android-ndk-r..*-linux.zip" | sed "/\"/d")"
-    printf "${CY0}Download latest version: ${url}\n"
+    echo -e "${CY0}Download latest version: ${url}"
   fi
 fi
 
 if [ -d "${ANDROID_NDK_HOME}" ]; then
   
-  ANDROID_NDK_RELEASE="$(basename ${ANDROID_NDK_HOME})"
-  ndk_root="$(dirname ${ANDROID_NDK_HOME})"
+  ANDROID_NDK_RELEASE="$(basename "${ANDROID_NDK_HOME}")"
+  ndk_root="$(dirname "${ANDROID_NDK_HOME}")"
   ndk_update=false
   ndk_download=false
   ndk_latest="$(curl -sL https://developer.android.com/ndk/downloads | grep -oP '(?<=ndkVersion..)\d+\.\d+\.\d+.*(?=")' | head -n1)"
   if [ "${ANDROID_NDK_RELEASE}" = "${ndk_latest}" ]; then
     status="(updated)"
-  elif [ "$(ls $ndk_root | tail -n1)" == "${ndk_latest}" ]; then
+  elif [ "$(ls ${ndk_root} | tail -n1)" == "${ndk_latest}" ]; then
     status="${CY1} found ${ndk_latest}${C0} at ${ndk_root}/${ndk_latest}"
     ndk_update=true
   else
@@ -260,8 +332,8 @@ if [ -d "${ANDROID_NDK_HOME}" ]; then
   XB_NDK_CLANG_VERSION="$(${XB_NDK_CLANG} -dumpversion)"
  
   cmake_platforms="${ANDROID_NDK_HOME}/build/cmake/platforms.cmake"
-  XB_NDK_MIN_PLATFORM_LEVEL="$(grep -oP '(?<=NDK_MIN_PLATFORM_LEVEL ")[0-9]+' ${cmake_platforms})"
-  XB_NDK_MAX_PLATFORM_LEVEL="$(grep -oP '(?<=NDK_MAX_PLATFORM_LEVEL ")[0-9]+' ${cmake_platforms})"
+  XB_NDK_MIN_PLATFORM_LEVEL="$(grep -oP '(?<=NDK_MIN_PLATFORM_LEVEL ")[0-9]+' "${cmake_platforms}")"
+  XB_NDK_MAX_PLATFORM_LEVEL="$(grep -oP '(?<=NDK_MAX_PLATFORM_LEVEL ")[0-9]+' "${cmake_platforms}")"
   NDK_API_DEFAULT="${XB_NDK_MAX_PLATFORM_LEVEL}"
   
   printf "${CH}${XBTAB}: ${C0}%s\n" "  found at" "${ANDROID_NDK_HOME}"
@@ -269,72 +341,101 @@ if [ -d "${ANDROID_NDK_HOME}" ]; then
   printf "${CH}${XBTAB}: ${C0}%s\n" "  clang version" "${XB_NDK_CLANG_VERSION}"
   printf "${CH}${XBTAB}: ${C0}%s\n" "  api range" "${XB_NDK_MIN_PLATFORM_LEVEL} to ${XB_NDK_MAX_PLATFORM_LEVEL}"
 
-  printf "\n${CC0} Check NDK symlinks\n"
+  echo -e "\n${CC0} Check NDK symlinks"
 
-  c_arch=('aarch64' 'arm' 'i686' 'x86_64')
+  #c_arch=('aarch64' 'arm' 'i686' 'x86_64')
   c_abi=('arm64-v8a' 'armeabi-v7a' 'x86' 'x86_64')
   c_clang=('aarch64-linux-android' 'armv7a-linux-androideabi' 'i686-linux-android' 'x86_64-linux-android')
   c_lib=('aarch64-linux-android' 'arm-linux-androideabi' 'i686-linux-android' 'x86_64-linux-android')
 
   for i in 0 1 2 3; do
     t="${c_lib[${i}]}"
-    printf "  ${CH}${t}${C0}\n"
-    dir_toolchain="/usr/${t}"
+    printf "  ${CH}%s${C0}\n" "${t}"
+    dst_root="/usr/${t}"
+    dst_bin="${dst_root}/bin"
+    dst_lib="${dst_root}/lib"
     
     # create cross arch dir at /usr
-    if [ ! -d "/usr/${t}/bin" ]; then
-      sudo mkdir -p "/usr/${t}/bin"
-      printf "    ${CD}created /usr/${t}/bin"  
+    if [ ! -d "${dst_bin}" ]; then
+      sudo mkdir -p "${dst_bin}"
+      printf "    ${CD}created %s" "${dst_bin}"  
     fi
 
-    tc_path="\${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/${ndk_build,,}/bin"
-    tc_api="\${API:=${NDK_API_DEFAULT}}"
+    #tc_path="\${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/${ndk_build,,}/bin"
+    #tc_api="\${API:=${NDK_API_DEFAULT}}"
     # synthax check_ndk_wrapper [--overwrite] <clang|clang++> <triplet> <dest>
-    check_ndk_wrapper --overwrite "clang" "${c_clang[${i}]}" "/usr/${t}/bin/clang"
-    check_ndk_wrapper --overwrite "clang++" "${c_clang[${i}]}" "/usr/${t}/bin/clang++"
-    # test 
-    printf "    ${C0}clang/clang++${CD} wrapper: $(/usr/${t}/bin/clang -dumpversion >/dev/null && echo -ne "${Cw}works${CD}" || echo -ne "${CR1}not working${CD}" )\n"
+    check_ndk_wrapper --overwrite "clang" "${c_clang[${i}]}" "${dst_bin}/clang"
+    check_ndk_wrapper --overwrite "clang++" "${c_clang[${i}]}" "${dst_bin}/clang++"
+    # test
+    printf "    ${C0}clang/clang++${CD} wrapper: %s" "$("${dst_bin}/clang" -dumpversion >/dev/null && echo -e "${CW}works${CD}" || echo -e "${CR1}not working${CD}" )"
 
-    check_ndk_symlink "/usr/${t}/bin/ld" && sudo ln -sfn "${XB_NDK_TOOLCHAIN}/bin/ld" "/usr/${t}/bin/ld"
-    printf "    ${C0}ld${CD} at /usr/${t}/bin/ld: ${C0}$(/usr/${t}/bin/ld --version)${CD}\n"
-    check_ndk_symlink "/usr/${t}/bin/yasm" && sudo ln -sfn "${XB_NDK_TOOLCHAIN}/bin/yasm" "/usr/${t}/bin/yasm"
-    printf "    ${C0}yasm${CD} at /usr/${t}/bin/yasm: ${C0}$(/usr/${t}/bin/yasm --version | head -n1)${CD}\n"
+    check_ndk_symlink_dir --quiet "${dst_bin}/ld" "${XB_NDK_TOOLCHAIN}/bin/ld" \
+      "${ANDROID_NDK_HOME}" "ANDROID_NDK_HOME"
+    printf ": ${C0}%s${CD}" "$("${dst_bin}/ld" --version)"
+    check_ndk_symlink_dir --quiet "${dst_bin}/yasm" "${XB_NDK_TOOLCHAIN}/bin/yasm" \
+      "${ANDROID_NDK_HOME}" "ANDROID_NDK_HOME"
+    printf ": ${C0}%s${CD}" "$("${dst_bin}/yasm" --version | head -n1)"
     
-    printf "    ${C0}binutils:${CD} "
+    echo -ne "\n    ${C0}binutils:${CD} "
     for j in as ar nm addr2line objcopy objdump ranlib readelf readobj size strings strip; do
-      check_ndk_symlink "/usr/${t}/bin/${j}" && sudo ln -sfn "${XB_NDK_TOOLCHAIN}/bin/llvm-${j}" "/usr/${t}/bin/${j}"
-      printf "${j} "
+      check_ndk_symlink "${dst_bin}/${j}" && sudo ln -sfn "${XB_NDK_TOOLCHAIN}/bin/llvm-${j}" "${dst_bin}/${j}"
+      test $? && echo -ne "${j} " || echo -ne "${CR1}${j}${CD} "
     done
-    
-    check_ndk_symlink "/usr/${t}/sysroot" && sudo ln -sfn "${XB_NDK_SYSROOT}" "/usr/${t}/sysroot"
-    printf "\n    ${C0}sysroot${CD} symlink /usr/${t}/sysroot -> ${XB_NDK_SYSROOT//${ANDROID_NDK_HOME}/NDK_HOME}"
 
-    check_ndk_symlink "/usr/${t}/include" && sudo ln -sfn "${XB_NDK_SYSROOT}/usr/include" "/usr/${t}/include"
-    printf "\n    ${C0}include${CD} symlink /usr/${t}/include -> NDK_SYSROOT/usr/include"
+    check_ndk_symlink_dir "/usr/${t}/sysroot" "${XB_NDK_SYSROOT}" \
+      "${ANDROID_NDK_HOME}" "ANDROID_NDK_HOME"
+    check_ndk_symlink_dir "/usr/${t}/include" "${XB_NDK_SYSROOT}/usr/include" \
+      "${XB_NDK_SYSROOT}" "NDK_SYSROOT"
+    check_ndk_symlink_dir "/usr/${t}/lib" "${XB_NDK_SYSROOT}/usr/lib/${c_lib[${i}]}" \
+      "${XB_NDK_SYSROOT}" "NDK_SYSROOT"
+    check_ndk_symlink_dir "${dst_root}/local" "${dir_root}/builds/android/${c_abi[${i}]}"
     
-    check_ndk_symlink "/usr/${t}/lib" && sudo ln -sfn "${XB_NDK_TOOLCHAIN}/sysroot/usr/lib/${c_lib[${i}]}" "/usr/${t}/lib"
-    printf "\n    ${C0}lib${CD} symlink /usr/${t}/lib -> NDK_SYSROOT/usr/lib/${c_lib[${i}]}"
+    if [ ! -f "${dst_lib}/libpthread.a" ]; then
+      sudo "${dst_bin}/ar" cr "${dst_lib}/libpthread.a"
+    fi
+    printf "\n    ${C0}libthread${CD} %s" "${dst_lib}/libpthread.a"
     
-    if [ ! -d "${dir_root}/builds/android/${c_abi[${i}]}" ]; then
-      mkdir -p "${dir_root}/builds/android/${c_abi[${i}]}"
+    if [ ! -f "${dst_lib}/librt.a" ]; then
+      sudo "${dst_bin}/ar" cr "${dst_lib}/librt.a"
     fi
-
-    [ -d "/usr/${t}/local" ] && sudo unlink /usr/${t}/local
-    sudo ln -sf "${dir_root}/builds/android/${c_abi[${i}]}" "/usr/${t}/local"
-    printf "\n    ${C0}local${CD} created at /usr/${t}/local -> ${dir_root}/builds/android/${c_abi[${i}]}"
-
-    if [ ! -f "/usr/${t}/lib/libpthread.a" ]; then
-      sudo /usr/${t}/bin/ar cr "/usr/${t}/lib/libpthread.a"
-    fi
-    printf "\n    ${C0}libthread${CD} /usr/${t}/lib/libpthread.a"
-    if [ ! -f "/usr/${t}/lib/librt.a" ]; then
-      sudo /usr/${t}/bin/ar cr "/usr/${t}/lib/librt.a"
-    fi
-    printf "\n    ${C0}librt${CD} /usr/${t}/lib/librt.a"
+    printf "\n    ${C0}librt${CD} %s" "${dst_lib}/librt.a"
+    
     echo -e "\n${C0}    toolchain at /usr/${t} ${CH}ok${C0}\n"
 done
 printf "${CH}%-20s: ${C0}%s\n" '  all toolchain symlinks' ok
 fi
 
+#exit 0
 
+# Mingw LLCM compiler
 
+echo -e "\n${CC1}${b}LLVM-MINGW Clang compiler"
+XB_LLVM_MINGW_LATEST="$(curl -sL "https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
+if [ -z "${LLVM_MINGW_HOME}" ]; then
+  w64clang=$(findname "aarch64-w64-mingw32-clang" "~" "/")
+  if [ -z "${w64clang}" ]; then
+    promptYN " not found. Install?" && install_llvm_mingw
+  else
+    export LLVM_MINGW_HOME=$(dirname $(dirname $w64clang))
+  fi
+fi 
+
+if [ -n "${LLVM_MINGW_HOME}" ]; then
+    printf "${CH}%-20s: ${C0}%s\n" "  found at" ${LLVM_MINGW_HOME}
+    [ -f "${LLVM_MINGW_HOME}/version" ] || echo "$XB_LLVM_MINGW_LATEST" >>"${LLVM_MINGW_HOME}/version"
+    LLVM_MINGW_REL=$(cat ${LLVM_MINGW_HOME}/version)
+    printf "${CH}%-20s: ${C0}%s " '  release' ${LLVM_MINGW_REL}
+    if [ "${LLVM_MINGW_REL}" == "${XB_LLVM_MINGW_LATEST}" ]; then
+        echo -e "(updated)"
+    else
+        echo -e "${CY1} latest is ${XB_LLVM_MINGW_LATEST}${C0}"
+    fi
+
+    CLANG_MINGW_VERSION_FULL=$(${LLVM_MINGW_HOME}/bin/clang -dumpversion)
+    CLANG_MINGW_VERSION=${llvm_mingw_clang_version%%\.*}
+    printf "${CH}%-20s: ${C0}%s\n" '  clang' "${CLANG_MINGW_VERSION_FULL}"
+
+    
+    # check and create symlinks in toolchains dir if needed
+    llvm_mingw_check_symlinks
+fi
